#!/bin/sh

qhmc="../../bin/qhmc"
hmc="../../hmc"

export OMP_NUM_THREADS=1
opts="nx=8;nt=16"
#opts="$opts;beta=5.5;masses={-0.8254, -0.75};ngsteps=192;nfsteps={8,32}"
opts="$opts;beta=5.5;masses={-0.4086,-0.37};ngsteps=192;nfsteps={8,32}"
opts="$opts;aniso={xi0=2.38,nu=1,gmom=2.4}"
opts="$opts;ntraj=1000"
opts="$opts;noMG=true"
opts="$opts;warmup=100"

t="MPaniso4x8.out"
stamp=`date +%Y%m%d%H%M%S`
echo $opts > $t.$stamp 
$qhmc -e "$opts" $hmc/wilson.lua >> $t.$stamp
