#!/bin/sh

p='$i'
if [ "X$1" = "X-p" ]; then
  p="$2"
  shift 2
fi

tag=$1
shift
if [ "X$tag" = "X" ]; then
  echo "$0 <tag> <files...>"
  exit -1
fi

fs=`\ls -1 "$@" |sort -n -t . -k 2`
echo $fs

get() {
  for f in $fs; do
    grep "$tag" $f
  done
}

ave() {
awk '
{
  for(i=1; i<=NF; i++) {
    n[i] += 1;
    v = '$p';
    s[i] += v;
    s2[i] += v*v;
    l[i] = $i;
  }
}
END{
  printf("# N = %i\n", n[1]);
  for(i=1; n[i]>0; i++) {
    if(match(l[i],"[a-zA-Z:=]")>0) {
      printf("%s ", l[i]);
    } else {
      printf("%-12.6g ", s[i]/n[i]);
    }
  }
  printf("\n");
  for(i=1; n[i]>0; i++) {
    if(match(l[i],"[a-zA-Z:=]")>0) {
      printf("%*c ", length(l[i]), " ");
    } else {
      a = s[i]/n[i];
      a2 = s2[i]/n[i];
      e = sqrt((a2-a*a)/(n[i]-1));
      printf("%-12.6g ", e);
    }
  }
  printf("\n");
}
'
}

n=`get |wc -l`
n9=$((9*n/10))
n8=$((8*n/10))
n2=$((n/2))
get |ave
get |tail -n $n9 |ave
get |tail -n $n8 |ave
get |tail -n $n2 |ave
