#!/bin/sh

qhmc="../../main/qhmc"
hmc="../../hmc"
t="aniso.out"

export OMP_NUM_THREADS=1

opts="beta=5.5;mass=0.2;ngsteps=200;nfsteps={200}"
opts="$opts;aniso={xi0=2.38,nu=1,gmom=2.4}"
opts="$opts;ntraj=1"
opts="$opts;noMG=true"

#$qhmc $hmc/wilson.lua
#$qhmc -e "ngsteps=60;nfsteps={20}" $hmc/wilson.lua
#$qhmc -e "ngsteps=150;nfsteps={50}" $hmc/wilson.lua
$qhmc -e "$opts" $hmc/wilson.lua
#$qhmc -e "beta=5.6;mass=0.2;ngsteps=100;nfsteps={100}" $hmc/wilson.lua
#$qhmc -e "ngsteps=600;nfsteps={200}" $hmc/wilson.lua
#$qhmc -e "doTrace=false;tau=1;ntraj=20;beta=4;mass=0.5" $hmc/wilson.lua
