#!/bin/sh

qhmc="../../main/qhmc"
hmc="../../hmc"

#fnin="su3_leapfrog.1.sample-in"
fnin="su3_rhmc_hisq.1.sample-in0"
fnout="test.out"

$qhmc $hmc/milc.lua $fnin -qmp-geom 1 1 1 1 >$fnout"0"

#$qhmc $hmc/milc.lua su3_rhmc_hisq.1.sample-in0 -qmp-geom 1 1 1 1 >$t"0"

#OMP_NUM_THREADS=1 mpirun -np 2 $qhmc $hmc/milc.lua su3_rhmc_hisq.1.sample-in0 -qmp-geom 1 1 1 2 >$t"0"
#OMP_NUM_THREADS=1 mpirun -np 2 $qhmc $hmc/milc.lua su3_rhmc_hisq.1.sample-in1 -qmp-geom 1 1 1 2 >$t"1"
#diff -I sec $t"0" su3_rhmc_hisq.1.sample-out0
#diff -I sec $t"1" su3_rhmc_hisq.1.sample-out1

#$qhmc -e 'force_filter=1' $hmc/milc.lua su3_rhmc_hisq.1.sample-in >$t

#OMP_NUM_THREADS=1 mpirun -np 2 $qhmc -e 'checkReverse=true' $hmc/milc.lua su3_rhmc_hisq.1.sample-in2 -qmp-geom 1 1 1 2 >$t


#OMP_NUM_THREADS=1 mpirun -np 2 $qhmc -e "stdoutfile=\"$t.%job\"" $hmc/milc.lua su3_rhmc_hisq.1.sample-in%job -qmp-geom 1 1 1 2 -qmp-job 1 1 1 2

#OMP_NUM_THREADS=1 mpirun -np 4 $qhmc -e "stdoutfile=\"$t%job\"" $hmc/milc.lua su3_rhmc_hisq.1.sample-in%job -qmp-geom 1 1 2 2 -qmp-job 1 1 2 1
#diff -I sec $t"0" su3_rhmc_hisq.1.sample-out0
#diff -I sec $t"1" su3_rhmc_hisq.1.sample-out1
