#!/bin/sh

fs=`\ls -1 "$@" |sort -n -t . -k 2`
echo $fs

get() {
  k="$1"
  a=`cat $fs |tail -n +$k |grep -c ACCEPT`
  r=`cat $fs |tail -n +$k |grep -c REJECT`
  t=$((a+r))
  f=`echo $a / $t |bc -l |xargs printf "%g"`
  echo "A/R: $a $r / $t = $f"
}

n=`cat $fs |wc -l`
n1=$((1+n/4))
n2=$((1+n/2))
n3=$((1+3*n/4))

get 1
get $n1
get $n2
get $n3
