#!/bin/sh

qhmc="../../main/qhmc"
hmc="../../hmc"
t="test.out"

export OMP_NUM_THREADS=1

#opts="beta=5.6"
opts="beta=11.028"
opts="$opts;nx=8"
opts="$opts;nt=8"
#opts="$opts;mass=0.2"
opts="$opts;ngsteps=50"
#opts="$opts;nfsteps={50}"
opts="$opts;ntraj=10"
#opts="$opts;noMG=true"

#$qhmc $hmc/wilson.lua
#$qhmc -e "ngsteps=60;nfsteps={20}" $hmc/wilson.lua
#$qhmc -e "ngsteps=150;nfsteps={50}" $hmc/wilson.lua
$qhmc -e "$opts" $hmc/qwilson.lua
#$qhmc -e "beta=5.6;mass=0.2;ngsteps=100;nfsteps={100}" $hmc/wilson.lua
#$qhmc -e "ngsteps=600;nfsteps={200}" $hmc/wilson.lua
#$qhmc -e "doTrace=false;tau=1;ntraj=20;beta=4;mass=0.5" $hmc/wilson.lua
